MacPass/de.lproj/DatabaseSettingsWindow.strings
MacPass/en.lproj/DatabaseSettingsWindow.strings
MacPass/fr.lproj/DatabaseSettingsWindow.strings
MacPass/nl.lproj/DatabaseSettingsWindow.strings
MacPass/zh-Hans.lproj/DatabaseSettingsWindow.strings

sed -i '' s/Maxium/Maximum/g MacPass/**/DatabaseSettingsWindow.strings

Fix spelling error of the word Maxium to Maximum

---

MacPass/Base.lproj/IntegrationSettings.xib

Fixed typo in settings>integrations

---

MacPass/MPPasswordCreatorViewController.m
MacPass/NSString+MPPasswordCreation.h
MacPass/NSString+MPPasswordCreation.m

As discussed in issue #355, I changed the behaviour of the custom character set in password generation. It is now possible to choose one of the preset characters sets AND specify custom characters.

Improved password generation UI as suggested in issue #355

---

README.md

I was just passing through and saw a small typo. I don't know the etiquette for something like that so hopefully this isn't out of line.

Correct spelling mistake.

---

MacPass/Base.lproj/PasswordCreatorView.xib
MacPass/NSString+MPPasswordCreation.m

A bugfix + missed UI behavior for the entropy calculation pull request from a few days back

Quick is not always right.

---

MacPass/sp.lproj/Credits.rtf
MacPass/sp.lproj/DatabaseSettingsWindow.strings
MacPass/sp.lproj/DatePickingView.strings
MacPass/sp.lproj/EntryInspectorView.strings
MacPass/sp.lproj/GeneralSettings.strings

Translation

---

MacPass/sp.lproj/Credits.rtf
MacPass/sp.lproj/DatabaseSettingsWindow.strings

I noticed there's no Spanish language here. So, I'm making my own.

New Spanish localisation folder

---

index.md

ansered=>answered

---

index.md

Same as [PR #660](https://github.com/mstarke/MacPass/pull/660) but for gh-pages.

cd into MacPass prior to running carthage

---

MacPass/es.lproj/ContextBar.strings
MacPass/es.lproj/Credits.rtf
MacPass/es.lproj/DuplicateEntryOptionsWindow.strings
MacPass/es.lproj/EntryInspectorView.strings
MacPass/es.lproj/GeneralSettings.strings
MacPass/es.lproj/GroupInspectorView.strings
MacPass/es.lproj/IntegrationSettings.strings
MacPass/es.lproj/Localizable.strings
MacPass/es.lproj/MainMenu.strings
MacPass/es.lproj/PasswordEditWindow.strings
MacPass/es.lproj/PluginSettings.strings
MacPass/es.lproj/ReferenceBuilderView.strings
MacPass/es.lproj/WorkflowSettings.strings

Improved or added ES localisations

---

CONTRIBUTE.md

I added a contribute file with the description of how to make translations. Might be helpful for another contributor.
Of course also other guidelines for contributing can be added in here.

Added a contribute file with the workflow for translations

---

MacPass/nl.lproj/AutotypeBuilderView.strings
MacPass/nl.lproj/AutotypeCandidateSelectionView.strings
MacPass/nl.lproj/DatabaseSettingsWindow.strings
MacPass/nl.lproj/EntryInspectorView.strings
MacPass/nl.lproj/GeneralSettings.strings
MacPass/nl.lproj/GroupInspectorView.strings
MacPass/nl.lproj/IntegrationSettings.strings
MacPass/nl.lproj/Localizable.strings
MacPass/nl.lproj/PasswordCreatorView.strings
MacPass/nl.lproj/PluginSettings.strings
MacPass/nl.lproj/WorkflowSettings.strings

Dear Michael,
Based on how my translation #714 / #715 works out in your latest continuous release of 3 March 2018, I made some improvements. There may be more tweaks coming, so please keep this pull request open until just before your next release.
Best regards!
Frank

Improved Dutch localization

---

MacPass.xcodeproj/project.pbxproj
MacPass/sv-SE.lproj/AutotypeBuilderView.strings
MacPass/sv-SE.lproj/AutotypeCandidateSelectionView.strings
MacPass/sv-SE.lproj/ContextBar.strings
MacPass/sv-SE.lproj/Credits.rtf
MacPass/sv-SE.lproj/DatabaseSettingsWindow.strings
MacPass/sv-SE.lproj/DatePickingView.strings
MacPass/sv-SE.lproj/DuplicateEntryOptionsWindow.strings
MacPass/sv-SE.lproj/EntryInspectorView.strings
MacPass/sv-SE.lproj/GeneralSettings.strings
MacPass/sv-SE.lproj/GroupInspectorView.strings
MacPass/sv-SE.lproj/IconSelection.strings
MacPass/sv-SE.lproj/InfoPlist.strings
MacPass/sv-SE.lproj/InspectorView.strings
MacPass/sv-SE.lproj/IntegrationSettings.strings
MacPass/sv-SE.lproj/Localizable.strings
MacPass/sv-SE.lproj/Localizable.stringsdict
MacPass/sv-SE.lproj/MainMenu.strings
MacPass/sv-SE.lproj/PasswordCreatorView.strings
MacPass/sv-SE.lproj/PasswordEditWindow.strings
MacPass/sv-SE.lproj/PasswordInputView.strings
MacPass/sv-SE.lproj/PickcharView.strings
MacPass/sv-SE.lproj/PickfieldView.strings
MacPass/sv-SE.lproj/PluginSettings.strings
MacPass/sv-SE.lproj/ReferenceBuilderView.strings
MacPass/sv-SE.lproj/UpdateSettings.strings
MacPass/sv-SE.lproj/WelcomeWindow.strings
MacPass/sv-SE.lproj/WorkflowSettings.strings
MacPassTests/sv-SE.lproj/InfoPlist.strings

May not be perfect, but dogfooded for a week, and some inspiration drawn from the Swedish translation of Keepass 2.x...

Initial version of Swedish translation

---

MacPass.xcodeproj/project.pbxproj
MacPass/pl.lproj/AutotypeBuilderView.strings
MacPass/pl.lproj/AutotypeCandidateSelectionView.strings
MacPass/pl.lproj/ContextBar.strings
MacPass/pl.lproj/DatabaseSettingsWindow.strings
MacPass/pl.lproj/DuplicateEntryOptionsWindow.strings
MacPass/pl.lproj/EntryInspectorView.strings
MacPass/pl.lproj/GeneralSettings.strings
MacPass/pl.lproj/GroupInspectorView.strings
MacPass/pl.lproj/InfoPlist.strings
MacPass/pl.lproj/InspectorView.strings
MacPass/pl.lproj/IntegrationSettings.strings
MacPass/pl.lproj/Localizable.strings
MacPass/pl.lproj/Localizable.stringsdict
MacPass/pl.lproj/MainMenu.strings
MacPass/pl.lproj/PasswordCreatorView.strings
MacPass/pl.lproj/PasswordInputView.strings
MacPass/pl.lproj/PickfieldView.strings
MacPass/pl.lproj/PluginDataView.strings
MacPass/pl.lproj/PluginSettings.strings
MacPass/pl.lproj/ReferenceBuilderView.strings
MacPass/pl.lproj/UpdateSettings.strings
MacPass/pl.lproj/WorkflowSettings.strings

I've updated the translation and fixed some typos. Also, thank you everyone for working on this awesome project! 😉

Update Polish translation

---

README.md

Just a small typo, but why not right ;)

[docs] Typo

---

MacPass.xcodeproj/project.pbxproj
MacPass/MPAppDelegate.m
MacPass/MPDocumentWindowController.h
MacPass/MPDocumentWindowController.m
MacPass/MPPasswordInputController.h
MacPass/MPPasswordInputController.m
MacPass/MPTouchBarButtonCreator.h
MacPass/MPTouchBarButtonCreator.m
MacPass/NSTextView+MPTouchBarExtension.h
MacPass/NSTextView+MPTouchBarExtension.m
MacPass/de.lproj/Localizable.strings
MacPass/en.lproj/Localizable.strings

Hey there,
this is my WIP for Touch Bar support.
It addresses issue #614 .
But since this is pretty much the first time that I am working with objective c, I'd like to get your input early if this looks good or if im off somewhere with my coding style, location of imports, fields and methods or something.

Add touchbar support

---

MacPass.xcodeproj/project.pbxproj
MacPass/zh-Hans.lproj/AutotypeDoctorReportViewController.strings
MacPass/zh-Hans.lproj/ContextBar.strings
MacPass/zh-Hans.lproj/DatabaseSettingsWindow.strings
MacPass/zh-Hans.lproj/DuplicateEntryOptionsWindow.strings
MacPass/zh-Hans.lproj/InfoPlist.strings
MacPass/zh-Hans.lproj/InspectorView.strings
MacPass/zh-Hans.lproj/IntegrationPreferences.strings
MacPass/zh-Hans.lproj/Localizable.strings
MacPass/zh-Hans.lproj/Localizable.stringsdict
MacPass/zh-Hans.lproj/PluginDataView.strings
MacPass/zh-Hans.lproj/WorkflowPreferences.strings

I just found that there are so many things I've not really used in MacPass 😂 
@mstarke Could you please tell me where `PICKCHAR_INFO_MESSAGE_PICK_CHARACTERS` is used in MacPass?

Update zh-Hans localization

---

MacPass.xcodeproj/project.pbxproj
MacPass/ru.lproj/AutotypeDoctorReportViewController.strings
MacPass/ru.lproj/Localizable.strings

Added missed localizable strings for Russian language

Fixed missed localizations

---

MacPass/MPOverlayWindowController.m

Fix #982
Now the window looks much better

Fixed overlay window image color

---

MacPass/zh-Hant.lproj/AutotypeBuilderView.strings
MacPass/zh-Hant.lproj/AutotypeCandidateSelectionView.strings
MacPass/zh-Hant.lproj/AutotypeDoctorReportViewController.strings
MacPass/zh-Hant.lproj/ContextBar.strings
MacPass/zh-Hant.lproj/DatabaseSettingsWindow.strings
MacPass/zh-Hant.lproj/DatePickingView.strings
MacPass/zh-Hant.lproj/DuplicateEntryOptionsWindow.strings
MacPass/zh-Hant.lproj/EntryInspectorView.strings
MacPass/zh-Hant.lproj/GeneralPreferences.strings
MacPass/zh-Hant.lproj/GroupInspectorView.strings
MacPass/zh-Hant.lproj/IconSelection.strings
MacPass/zh-Hant.lproj/InfoPlist.strings
MacPass/zh-Hant.lproj/InspectorView.strings
MacPass/zh-Hant.lproj/IntegrationPreferences.strings
MacPass/zh-Hant.lproj/Localizable.strings
MacPass/zh-Hant.lproj/Localizable.stringsdict
MacPass/zh-Hant.lproj/MainMenu.strings
MacPass/zh-Hant.lproj/PasswordCreatorView.strings
MacPass/zh-Hant.lproj/PasswordEditWindow.strings
MacPass/zh-Hant.lproj/PasswordInputView.strings
MacPass/zh-Hant.lproj/PluginDataView.strings
MacPass/zh-Hant.lproj/PluginPreferences.strings
MacPass/zh-Hant.lproj/PluginRepositoryBrowserView.strings
MacPass/zh-Hant.lproj/ReferenceBuilderView.strings
MacPass/zh-Hant.lproj/SavePanelAccessoryView.strings
MacPass/zh-Hant.lproj/UpdatePreferences.strings
MacPass/zh-Hant.lproj/WelcomeView.strings
MacPass/zh-Hant.lproj/WorkflowPreferences.strings

Basically throw zh-Hans into machine translation with a few manual ones. (Thanks to everyone who've done the work.) 
Will fix any strange strings when I see them.

Initial zh-Hant translation

---

MacPass/Base.lproj/WelcomeView.xib

I've adjusted the WelcomeView to reflow better when the window is resized, so the left part is always properly centered. Also fixed all of the misplacements.
Before:
After:

Adjust WelcomeView layout

---

MacPass/fr.lproj/AutotypeCandidateSelectionView.strings
MacPass/fr.lproj/DuplicateEntryOptionsWindow.strings
MacPass/fr.lproj/EntryInspectorView.strings
MacPass/fr.lproj/GeneralPreferences.strings
MacPass/fr.lproj/InfoPlist.strings
MacPass/fr.lproj/InspectorView.strings
MacPass/fr.lproj/IntegrationPreferences.strings
MacPass/fr.lproj/Localizable.strings
MacPass/fr.lproj/MainMenu.strings
MacPass/fr.lproj/PickcharsView.strings
MacPass/fr.lproj/PluginPreferences.strings
MacPass/fr.lproj/PluginRepositoryBrowserView.strings
MacPass/fr.lproj/SavePanelAccessoryView.strings
MacPass/fr.lproj/WorkflowPreferences.strings

Made a few minor adjustments: typos, consistency
Added missing Favicon translation in General settings + missing translations in Workflow settings

Updated Translation (FR)
