- MacPass/de.lproj/MainMenu.strings
The word `fokussieren` had a missing s.
> Corrected the German translation

- MacPass/Base.lproj/DatabaseSettingsWindow.xib
Was listed as Maxium Size and Maxium Items. Fixed spelling to Maximum.
> Fixed typo in db settings > advanced

- README.md
Change to documentation:
Recursive init and update is required to correctly initialize second order dependencies (DDXMLDocument.h in KeePassKit/KissXML was not found).
> Fix for https://github.com/mstarke/MacPass/issues/386

- README.md
I've never built anything with Xcode, but wanted to run the master branch version of MacPass to be able to use MacPassHTTP. Unfortunately the exact steps for doing this weren't specified and a simple `xcodebuild` failed. So after some searching and trial and error I found a command that did exactly what I needed and added it to *README* for easy reference for others in a similar situation.
Please let me know if there's a better/shorter command for reaching the same result.
> Add xcode install command to README

- MacPass/NSString+MPPasswordCreation.m
When custom characters was used only the custom string was used in calculation. Now the character sets are merged with any custom characters.
> Fix entropy calculation

- MacPass/Base.lproj/PasswordCreatorView.xib
- MacPass/MPEntryInspectorViewController.m
This should implement the feature requested in #415.
Apologies for all the noise introduced by the new version of Xcode. I hope it's not causing troubles.
The change is quite simple. I just made the text field editable and added a number formatter to take care of input validation.
The only tricky part is the change I made to MPEntryInspectorViewController to prevent the popover to close if the input string is not valid.
Here there are some solution to the issue http://stackoverflow.com/questions/22211672/using-an-nsnumberformatter-in-an-nspopover I implemented the one that I though was the simplest and it's working perfectly fine. You might want to have a look at the other options and see if there is something you like more.
> Made the password length field editable in password generator

- MacPass/MPAutotypeDaemon.m
Implemented notification center message for autotype instead of the overlay. If the MacPass window is hidden, it will now remain hidden.
I'm new to the project, so I'm glad for feedback!
See issue #422
> Issue # 422 - Implemented notification center message 

- .travis.yml
- ci/build
Hey, 
yet another Travis PR. This time it uses the carthage dep manager / or rather just the build process as given in your README.
You may need to add a GitHub API Key into the Travis secure environment variables to bypass possible issues arising from the GitHub API limit being hit by Travis.
Also, Travis appears to offer an integration for various artifact providers, such as the GitHub releases, S3 or similar things.
> Enable Travis CI with carthage usage

- _config.yml
Setting correct github variables for zip and tar downloads to point to project (master) files instead of the gh-pages branch (see: https://github.com/pages-themes/midnight/issues/4). 
Closes #626
> Add correct github page variables

- MacPass/de.lproj/Localizable.strings
`Änderugnen` -> `Änderungen`
See http://www.duden.de/rechtschreibung/Aenderung
> Fixed a typo in German translation

- README.md
The command `carthage bootstrap --platform Mac` needs to be run from inside the MacPass project directory. This PR adds that missing line in the doc.
This is to avoid the following error:
```
*** No Cartfile.resolved found, updating dependencies
Failed to read file or folder at /Users/user/Cartfile: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/user/Cartfile, NSUnderlyingError=0x7ff676546e30 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```
> cd into MacPass prior to running carthage

- MacPass/NSString+MPPasswordCreation.m
Avoid a possible modulo bias in randomCharacter by using arc4random_uniform().
> Use arc4random_uniform() to avoid modulo bias.

- README.md
Build status badge used to point at a wrong (old?) URL. Fixed by changing URL to MacPass/MacPass.
> Fixes build status badge in README

- MacPass/fr.lproj/Localizable.strings
"Save" in this context, translated to French is "Enregistrer", not "Sauvegarder" (which means "to backup").
> Changed "Sauvegarder" => "Enregistrer"

- MacPass/MPPathControl.m
If we don't use the modal view, the user can put the file selection window to background, click 'Choose...' and open additional windows.
This can become confusing and the additional windows can stay there hanging through the app's lifecycle. Moreover, if we choose 'Choose...' from the drop down menu, after selecting a key file, the dialog displayed is currently modal, inline with this commit.
> Make keyfile selection window modal

- MacPass/de.lproj/GeneralSettings.strings
Add in GeneralSettings.strings "Enable Autosave" and "Close and open all documents for changes to take effect" in German.
Hope that's in the right format, this two points in general settings are not localized at the moment.
Best regards,
Jesse
> Updated german localization

- MacPass/MPPluginRepository.m
- MacPass/de.lproj/Localizable.strings
- MacPass/en.lproj/Localizable.strings
- MacPass/es.lproj/Localizable.strings
Fix the correct meaning of the NSLocalizedString constant for the alert button titles
> Fix localized string ambiguous with word allow/disallow

- MacPass.xcodeproj/project.pbxproj
- MacPass/Base.lproj/PasswordEditWindow.xib
- MacPass/de.lproj/DuplicateEntryOptionsWindow.strings
- MacPass/fr.lproj/DuplicateEntryOptionsWindow.strings
- MacPass/it.lproj/AutotypeBuilderView.strings
- MacPass/it.lproj/AutotypeCandidateSelectionView.strings
- MacPass/it.lproj/AutotypeDoctorReportViewController.strings
- MacPass/it.lproj/ContextBar.strings
- MacPass/it.lproj/DuplicateEntryOptionsWindow.strings
- MacPass/it.lproj/InfoPlist.strings
- MacPass/it.lproj/Localizable.strings
- MacPass/it.lproj/OpenPanelAccessoryView.strings
- MacPass/it.lproj/PasswordInputView.strings
- MacPass/it.lproj/PickcharsView.strings
- MacPass/it.lproj/PickfieldView.strings
- MacPass/it.lproj/PluginDataView.strings
- MacPass/it.lproj/PluginPreferences.strings
- MacPass/it.lproj/PluginRepositoryBrowserView.strings
- MacPass/it.lproj/SavePanelAccessoryView.strings
I've always modified translations directly in Xcode. Also XLIFFTool doesn't seem to work; I tried opening the included XLIFF file in #915 but it never responded, so I just edited the strings files directly. Let me know if that causes any issues.
The original strings file was missing multiple entries and had reordered the strings, so I overwrote the file completely to match the ordering in the English and German versions. Where possible, I reused the already present translations unless I felt they could be improved.
> Update Italian Localization

- MacPass.xcodeproj/project.pbxproj
- MacPass/fr.lproj/AutotypeBuilderView.strings
- MacPass/fr.lproj/AutotypeCandidateSelectionView.strings
- MacPass/fr.lproj/AutotypeDoctorReportViewController.strings
- MacPass/fr.lproj/ContextBar.strings
- MacPass/fr.lproj/DatabaseSettingsWindow.strings
- MacPass/fr.lproj/EntryInspectorView.strings
- MacPass/fr.lproj/GeneralPreferences.strings
- MacPass/fr.lproj/InfoPlist.strings
- MacPass/fr.lproj/IntegrationPreferences.strings
- MacPass/fr.lproj/Localizable.strings
- MacPass/fr.lproj/Localizable.stringsdict
- MacPass/fr.lproj/MainMenu.strings
- MacPass/fr.lproj/PasswordCreatorView.strings
- MacPass/fr.lproj/PasswordEditWindow.strings
- MacPass/fr.lproj/PasswordInputView.strings
- MacPass/fr.lproj/PickfieldView.strings
- MacPass/fr.lproj/PluginPreferences.strings
- MacPass/fr.lproj/PluginRepositoryBrowserView.strings
- MacPass/fr.lproj/ReferenceBuilderView.strings
- MacPass/fr.lproj/SavePanelAccessoryView.strings
- MacPass/fr.lproj/WorkflowPreferences.strings
First of all, thank you for maintaining this very useful app 🙂.
I **added 121 missing french translations** and **tweaked some existing one**.
The app is now **fully translated in French**, there is **no missing french strings** anymore.
Before:
After:
This will fix these 2 issues:
- https://github.com/MacPass/MacPass/issues/1015
- https://github.com/MacPass/MacPass/issues/1000
> Update all missing french localization

- MacPass/Base.lproj/GeneralPreferences.xib
- MacPass/MPGeneralPreferencesController.h
- MacPass/MPGeneralPreferencesController.m
- MacPass/MPIconHelper.m
- MacPass/MPSettingsHelper.h
- MacPass/MPSettingsHelper.m
- MacPass/PreferencesWindow.xib
- MacPass/en.lproj/Localizable.strings
There are multiple ways of how favicon of a website can be published:
- Have a `favicon.ico` file under the website root
- Set through `<link rel="shortcut icon" href="..." />` tag
- Set through `<link rel="icon" href="..." />` tag, or
- Set through platform-specific tags like `<link rel="apple-touch-icon" href="..." />`
Current implementation only supports first option, which does not work in many cases.
Instead of implementing favicon fetching logic from scratch, favicon fetching services can be used.
There are multiple of them, e.g.:
- https://icons.duckduckgo.com/ip3/www.google.com.ico
- https://www.google.com/s2/favicons?domain=www.google.com
This change switched from fetching favicon from the original host to DuckDuckGo.
> Use DuckDuckGo favicon service

- LICENSE.txt
- MacPass/Base.lproj/Credits.rtf
- README.md
Found some references to the previous organization. Nice to have no redirects.
> Update organization in GitHub URL

- MacPass/de.lproj/AutotypeCandidateSelectionView.strings
- MacPass/de.lproj/AutotypeDoctorReportViewController.strings
- MacPass/de.lproj/DatabaseSettingsWindow.strings
- MacPass/de.lproj/EntryInspectorView.strings
- MacPass/de.lproj/GeneralPreferences.strings
- MacPass/de.lproj/GroupInspectorView.strings
- MacPass/de.lproj/IconSelection.strings
- MacPass/de.lproj/InfoPlist.strings
- MacPass/de.lproj/IntegrationPreferences.strings
- MacPass/de.lproj/Localizable.strings
- MacPass/de.lproj/MainMenu.strings
- MacPass/de.lproj/OpenPanelAccessoryView.strings
- MacPass/de.lproj/PasswordCreatorView.strings
- MacPass/de.lproj/PluginDataView.strings
- MacPass/de.lproj/ReferenceBuilderView.strings
- MacPass/en.lproj/Localizable.strings
In order to do this finally correct, I have to thoroughly test the application and make sure, that the German text really expresses what is meant. For some cases I had to guess the context.
Further, I tried to improved the consistency, like "user" can be "Nutzer" or "Benutzer" (which is gender neutral, in fact, and the Left-or-Green-party-public-broadcast-versions "Nutzer*in" or "Nutzer:in" or "NutzerIn" or "Nutzer_in" or "Nutzende" or "Nutzerinnen und Nutzer" or "Nutzer and Nutzerinnen" or even "Nutzerinnen" or "Nutzerinnen und Nutzerinnen" are located between unnecessary and total nonsense). "Merge" might be "mischen" or here "zusammenführen" or "synchronisieren". Somebody translated "Autotype" with "Auto-Type", but I reverted that as it does not look helpful to me.
So, basically this …
> German localisation improved, one typo in US localisation corrected

- MacPass/Base.lproj/EntryInspectorView.xib
Apple enabled password autofill by default on Big Sur for NSSecureTextField.
This means that by clicking the password field in an entry in MacPass, an annoying "Passwords..." tooltip pops up.
By changing the secure text field's content type to "oneTimeCode", the default behavior is overridden and the autofill feature is disabled.
> fixed autofill on big sur for password field

- MacPass.xcodeproj/project.pbxproj
- MacPass/Base.lproj/IntegrationPreferences.xib
- MacPass/Base.lproj/PasswordInputView.xib
- MacPass/MPConstants.h
- MacPass/MPConstants.m
- MacPass/MPDocument.h
- MacPass/MPDocument.m
- MacPass/MPDocumentWindowController.m
- MacPass/MPIntegrationPreferencesController.m
- MacPass/MPPasswordInputController.h
- MacPass/MPPasswordInputController.m
- MacPass/MPSettingsHelper.h
- MacPass/MPSettingsHelper.m
- MacPass/MPTouchIdCompositeKeyStore.h
- MacPass/MPTouchIdCompositeKeyStore.m
- MacPass/MacPass.entitlements
This patch enables MacPass users to unlock their KeePass containers with TouchID. In contrast to #638,  the implementation does not store the master password directly into the keychain of macOS. Instead it creates a RSA 2048 key pair and uses the public key to encrypt the password. The encrypted password is then kept in memory as long as the MacPass process is alive.
The private key is then used on a subsequent unlock to decrypt the master password. macOS will only return the private key if the device is unlocked and a user, who`s fingerprints were enrolled at the time the key pair was created, authenticates via TouchID.
On every launch of MacPass the user has to supply the master password once for TouchID unlock to work. This is a trade of between security and convenience. But on macOS …
> TouchID unlock Feature for MacPass.
